[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cochise"
version = "0.0.1"
dependencies = [
    "langchain-openai>=0.3.1",
    "python-dotenv>=1.0.1",
    "rich>=13.9.2",
    "structlog>=25.1",
    "asyncssh",
    "jinja2"
]
requires-python = ">= 3.8"
