[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cochise"
version = "0.0.2"
dependencies = [
    "langchain-openai>=1.1.4",
    "langchain-google-genai>=4.1.2",
    "python-dotenv>=1.0.1",
    "rich>=14.2.0",
    "structlog>=25.5.0",
    "asyncssh",
    "jinja2"
]
requires-python = ">= 3.12"
